allowLocalFiles: true
inputDir: ./source
output: ./output
theme: cybertopia
# themeSet: ./assets/css
author: Marco Spinello
title: When AI goes off piste | Tales from the documentation pipelines
pdf: true
template: bespoke
options:
  looseYAML: false
  markdown:
    breaks: false
    watch: true
    html:
      enabled: true
      allowedTags:
        - div
        - iframe
        - video
      allowedAttributes:
        # Global attributes permitted for all (from your requirements)
        '*': [ 'class', 'id', 'style' ]
        # div-specific
        div: [ 'class', 'id', 'style' ]
        # iframe-specific
        iframe:
          - src
          - height
          - width
          - sandbox  # You control allowed values via content, e.g., sandbox="allow-presentation allow-same-origin"
          - class
          - id
          - style
        # video-specific
        video:
          - src
          - height
          - width
          - type
          - autoplay
          - controls
          - controlsList
          - crossorigin  # For use-credentials, you'll write: crossorigin="use-credentials"
          - class
          - id
          - style
